import type { PriceIndexRecord } from "./schema.ts";

// Mechanically generated from the canonical public Q3 2026 JSONL release.
export const MODEL_PRICE_SUMMARY: readonly PriceIndexRecord[] = [
  {
    "model": "DJI Mavic 3 Enterprise",
    "source_listing_labels": "DJI Mavic 3 Enterprise",
    "source_row_count": 1,
    "configurations_tracked": 1,
    "listed_price_low_usd": 16950,
    "listed_price_high_usd": 16950,
    "median_listed_price_usd": 16950,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3 Thermal",
    "source_listing_labels": "DJI Mavic 3 Thermal",
    "source_row_count": 1,
    "configurations_tracked": 1,
    "listed_price_low_usd": 16947,
    "listed_price_high_usd": 16947,
    "median_listed_price_usd": 16947,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Inspire 3",
    "source_listing_labels": "DJI Inspire 3",
    "source_row_count": 1,
    "configurations_tracked": 4,
    "listed_price_low_usd": 13358,
    "listed_price_high_usd": 20001,
    "median_listed_price_usd": 16603,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Matrice 4T",
    "source_listing_labels": "DJI Matrice 4T | DJI Matrice 4T (Customization)",
    "source_row_count": 2,
    "configurations_tracked": 2,
    "listed_price_low_usd": 13500,
    "listed_price_high_usd": 13500,
    "median_listed_price_usd": 13500,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Matrice 30T",
    "source_listing_labels": "DJI Matrice 30T",
    "source_row_count": 1,
    "configurations_tracked": 1,
    "listed_price_low_usd": 12213,
    "listed_price_high_usd": 12213,
    "median_listed_price_usd": 12213,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 2 Enterprise",
    "source_listing_labels": "DJI Mavic 2 Enterprise",
    "source_row_count": 1,
    "configurations_tracked": 1,
    "listed_price_low_usd": 3298,
    "listed_price_high_usd": 3298,
    "median_listed_price_usd": 3298,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3 Pro Cine",
    "source_listing_labels": "DJI Mavic 3 Pro Cine",
    "source_row_count": 1,
    "configurations_tracked": 8,
    "listed_price_low_usd": 2800,
    "listed_price_high_usd": 3936,
    "median_listed_price_usd": 3271,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 4 Pro",
    "source_listing_labels": "DJI Mavic 4 Pro",
    "source_row_count": 1,
    "configurations_tracked": 8,
    "listed_price_low_usd": 2280,
    "listed_price_high_usd": 3301,
    "median_listed_price_usd": 2840,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3 Pro",
    "source_listing_labels": "DJI Mavic 3 Pro",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 1712,
    "listed_price_high_usd": 3354,
    "median_listed_price_usd": 2486,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3 Classic",
    "source_listing_labels": "DJI Mavic 3 Classic",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 2140,
    "listed_price_high_usd": 2721,
    "median_listed_price_usd": 2450,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3",
    "source_listing_labels": "DJI Mavic 3",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 1481,
    "listed_price_high_usd": 2601,
    "median_listed_price_usd": 1953,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 3 Cine",
    "source_listing_labels": "DJI Mavic 3 Cine",
    "source_row_count": 1,
    "configurations_tracked": 8,
    "listed_price_low_usd": 1496,
    "listed_price_high_usd": 2751,
    "median_listed_price_usd": 1916,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Inspire 1 V2.0",
    "source_listing_labels": "DJI Inspire 1 V2.0",
    "source_row_count": 1,
    "configurations_tracked": 2,
    "listed_price_low_usd": 1351,
    "listed_price_high_usd": 1501,
    "median_listed_price_usd": 1426,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Inspire 2",
    "source_listing_labels": "DJI Inspire 2",
    "source_row_count": 1,
    "configurations_tracked": 4,
    "listed_price_low_usd": 1160,
    "listed_price_high_usd": 1800,
    "median_listed_price_usd": 1410,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 5 Pro",
    "source_listing_labels": "DJI Mini 5 Pro",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 850,
    "listed_price_high_usd": 1500,
    "median_listed_price_usd": 1070,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Air 3S",
    "source_listing_labels": "DJI Air 3S",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 790,
    "listed_price_high_usd": 1320,
    "median_listed_price_usd": 1066,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Avata 360",
    "source_listing_labels": "DJI Avata 360",
    "source_row_count": 1,
    "configurations_tracked": 5,
    "listed_price_low_usd": 623,
    "listed_price_high_usd": 1150,
    "median_listed_price_usd": 920,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Inspire 1 V1.0",
    "source_listing_labels": "DJI Inspire 1 V1.0",
    "source_row_count": 1,
    "configurations_tracked": 1,
    "listed_price_low_usd": 860,
    "listed_price_high_usd": 860,
    "median_listed_price_usd": 860,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Air 3",
    "source_listing_labels": "DJI Air 3",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 591,
    "listed_price_high_usd": 1129,
    "median_listed_price_usd": 828,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 4 Pro",
    "source_listing_labels": "DJI Mini 4 Pro",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 461,
    "listed_price_high_usd": 850,
    "median_listed_price_usd": 672,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Avata",
    "source_listing_labels": "DJI Avata",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 180,
    "listed_price_high_usd": 701,
    "median_listed_price_usd": 650,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Avata 2",
    "source_listing_labels": "DJI Avata 2",
    "source_row_count": 1,
    "configurations_tracked": 4,
    "listed_price_low_usd": 199,
    "listed_price_high_usd": 1000,
    "median_listed_price_usd": 649,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Lito X1",
    "source_listing_labels": "DJI Lito X1",
    "source_row_count": 1,
    "configurations_tracked": 5,
    "listed_price_low_usd": 410,
    "listed_price_high_usd": 730,
    "median_listed_price_usd": 570,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Air 2S",
    "source_listing_labels": "DJI Air 2S",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 391,
    "listed_price_high_usd": 776,
    "median_listed_price_usd": 543,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Flip",
    "source_listing_labels": "DJI Flip",
    "source_row_count": 1,
    "configurations_tracked": 4,
    "listed_price_low_usd": 300,
    "listed_price_high_usd": 741,
    "median_listed_price_usd": 529,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 3 Pro",
    "source_listing_labels": "DJI Mini 3 Pro",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 380,
    "listed_price_high_usd": 740,
    "median_listed_price_usd": 516,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic Air 2",
    "source_listing_labels": "DJI Mavic Air 2",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 241,
    "listed_price_high_usd": 750,
    "median_listed_price_usd": 470,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 2",
    "source_listing_labels": "DJI Mavic 2",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 247,
    "listed_price_high_usd": 700,
    "median_listed_price_usd": 465,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic 2 Pro",
    "source_listing_labels": "DJI Mavic 2 Pro",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 276,
    "listed_price_high_usd": 700,
    "median_listed_price_usd": 455,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Neo 2",
    "source_listing_labels": "DJI Neo 2",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 200,
    "listed_price_high_usd": 730,
    "median_listed_price_usd": 421,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 3",
    "source_listing_labels": "DJI Mini 3",
    "source_row_count": 1,
    "configurations_tracked": 10,
    "listed_price_low_usd": 280,
    "listed_price_high_usd": 530,
    "median_listed_price_usd": 405,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Lito 1",
    "source_listing_labels": "DJI Lito 1",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 330,
    "listed_price_high_usd": 460,
    "median_listed_price_usd": 360,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Neo",
    "source_listing_labels": "DJI Neo",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 120,
    "listed_price_high_usd": 538,
    "median_listed_price_usd": 315,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic Pro Platinum",
    "source_listing_labels": "DJI Mavic Pro Platinum",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 250,
    "listed_price_high_usd": 380,
    "median_listed_price_usd": 307,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic Pro",
    "source_listing_labels": "DJI Mavic Pro",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 240,
    "listed_price_high_usd": 395,
    "median_listed_price_usd": 304,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 4K",
    "source_listing_labels": "DJI Mini 4K",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 221,
    "listed_price_high_usd": 330,
    "median_listed_price_usd": 270,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 2",
    "source_listing_labels": "DJI Mini 2",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 206,
    "listed_price_high_usd": 330,
    "median_listed_price_usd": 265,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini 2 SE",
    "source_listing_labels": "DJI Mini 2 SE",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 186,
    "listed_price_high_usd": 346,
    "median_listed_price_usd": 254,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mini SE",
    "source_listing_labels": "DJI Mini SE",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 157,
    "listed_price_high_usd": 290,
    "median_listed_price_usd": 239,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic Mini",
    "source_listing_labels": "DJI Mavic Mini",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 156,
    "listed_price_high_usd": 301,
    "median_listed_price_usd": 224,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Mavic Air",
    "source_listing_labels": "DJI Mavic Air",
    "source_row_count": 1,
    "configurations_tracked": 6,
    "listed_price_low_usd": 140,
    "listed_price_high_usd": 261,
    "median_listed_price_usd": 218,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Spark",
    "source_listing_labels": "DJI Spark",
    "source_row_count": 1,
    "configurations_tracked": 3,
    "listed_price_low_usd": 124,
    "listed_price_high_usd": 279,
    "median_listed_price_usd": 201,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  },
  {
    "model": "DJI Tello",
    "source_listing_labels": "DJI Tello",
    "source_row_count": 1,
    "configurations_tracked": 2,
    "listed_price_low_usd": 150,
    "listed_price_high_usd": 223,
    "median_listed_price_usd": 186,
    "snapshot_date": "2026-07-07",
    "release_quarter": "2026-Q3",
    "observation_unit": "aircraft model-level aggregate",
    "quality_status": "passed_publication_gate",
    "source_url": "https://reboot-hub.com/pages/reboot-hub-data",
    "methodology_note": "Aircraft model-level aggregate of published Reboot Hub catalog configuration prices on the snapshot date. Values are listed prices, not inventory claims or completed-sale prices.",
    "non_affiliation_note": "Reboot Hub is not affiliated with, endorsed by, or officially authorized by DJI."
  }
];
